port: env(PORT)

settings:
  loggerFormat: tiny
  session:
    store: '@foal/typeorm'

database:
  type: better-sqlite3
  database: './db.sqlite3'

binance:
  url: env(BINANCE_URL)
  apiKey: env(BINANCE_API_KEY)
  secret: env(BINANCE_SECRET)